# Module1-Exc2 - Getting and Knowing your Data

- Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries and read the dataset

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv('occ.csv')

### Step 2. See the first 25 entries

In [6]:
df.head(25)

    age gender     occupation zip_code
0    24      M     technician    85711
1    53      F          other    94043
2    23      M         writer    32067
3    24      M     technician    43537
4    33      F          other    15213
5    42      M      executive    98101
6    57      M  administrator    91344
7    36      M  administrator    05201
8    29      M        student    01002
9    53      M         lawyer    90703
10   39      F          other    30329
11   28      F          other    06405
12   47      M       educator    29206
13   45      M      scientist    55106
14   49      F       educator    97301
15   21      M  entertainment    10309
16   30      M     programmer    06355
17   35      F          other    37212
18   40      M      librarian    02138
19   42      F      homemaker    95660
20   26      M         writer    30068
21   25      M         writer    40206
22   30      F         artist    48197
23   21      F         artist    94533
24   39      M       engineer    55107

### Step 3. See the last 10 entries

In [9]:
df.tail(10)

     age gender     occupation zip_code
933   61      M       engineer    22902
934   42      M         doctor    66221
935   24      M          other    32789
936   48      M       educator    98072
937   38      F     technician    55038
938   26      F        student    33319
939   32      M  administrator    02215
940   20      M        student    97229
941   48      F      librarian    78209
942   22      M        student    77841

### Step 4. What is the number of observations in the dataset?

In [12]:
df.index

RangeIndex(start=0, stop=943, step=1)

In [15]:
df.shape

(943, 4)

In [13]:
print(f"There are {df.shape[0]} observation in the dataset")

There are 943 observation in the dataset

### Step 5. What is the number of columns in the dataset?

In [14]:
print(f"there are {df.shape[1]} number of colums")

there are 4 number of colums

### Step 6. Print the name of all the columns.

In [16]:
list(df.columns)

['age', 'gender', 'occupation', 'zip_code']

### Step 7. How is the dataset indexed?

In [17]:
df.index

RangeIndex(start=0, stop=943, step=1)

### Step 8. What is the data type of each column?

In [18]:
df.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### Step 9. Print only the occupation column

In [19]:
df['occupation']

0         technician
1              other
2             writer
3         technician
4              other
           ...
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: object

### Step 10. How many different occupations are in this dataset?

In [21]:
df['occupation'].unique()

array(['technician', 'other', 'writer', 'executive', 'administrator',
       'student', 'lawyer', 'educator', 'scientist', 'entertainment',
       'programmer', 'librarian', 'homemaker', 'artist', 'engineer',
       'marketing', 'none', 'healthcare', 'retired', 'salesman', 'doctor'],
      dtype=object)

### Step 11. What is the most frequent occupation?

In [24]:
df['occupation']

0         technician
1              other
2             writer
3         technician
4              other
           ...
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: object

In [35]:
stringer=lambda x: str(x)
lst_occupation = df['occupation'].apply(stringer).tolist()

In [37]:
freq = {}
for item in lst_occupation:
    if (item in freq):
        freq[item] += 1
    else:
        freq[item] = 1
 
print(freq)

{'technician': 27, 'other': 105, 'writer': 45, 'executive': 32, 'administrator': 79, 'student': 196, 'lawyer': 12, 'educator': 95, 'scientist': 31, 'entertainment': 18, 'programmer': 66, 'librarian': 51, 'homemaker': 7, 'artist': 28, 'engineer': 67, 'marketing': 26, 'none': 9, 'healthcare': 16, 'retired': 14, 'salesman': 12, 'doctor': 7}
student

In [38]:
Keymax = max(freq, key= lambda x: freq[x])
print(Keymax)

student

### Step 12. Summarize the DataFrame.

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         943 non-null    int64
 1   gender      943 non-null    object
 2   occupation  943 non-null    object
 3   zip_code    943 non-null    object
dtypes: int64(1), object(3)
memory usage: 29.6+ KB

### Step 13. Summarize all the columns

In [56]:
df.describe

<bound method NDFrame.describe of      age gender     occupation zip_code
0     24      M     technician    85711
1     53      F          other    94043
2     23      M         writer    32067
3     24      M     technician    43537
4     33      F          other    15213
..   ...    ...            ...      ...
938   26      F        student    33319
939   32      M  administrator    02215
940   20      M        student    97229
941   48      F      librarian    78209
942   22      M        student    77841

[943 rows x 4 columns]>

In [48]:
df['age'].unique()

array([24, 53, 23, 33, 42, 57, 36, 29, 39, 28, 47, 45, 49, 21, 30, 35, 40,
       26, 25, 32, 41,  7, 38, 20, 19, 27, 18, 22, 37, 16, 50, 31, 51, 17,
       48, 34, 43, 60, 55, 15, 61, 44, 54, 59, 46, 13, 52, 56, 14, 66, 62,
       11, 65, 68, 63, 64, 10, 73, 58, 69, 70])

In [49]:
df['gender'].unique()

array(['M', 'F'], dtype=object)

In [47]:
df['occupation'].unique()

array(['technician', 'other', 'writer', 'executive', 'administrator',
       'student', 'lawyer', 'educator', 'scientist', 'entertainment',
       'programmer', 'librarian', 'homemaker', 'artist', 'engineer',
       'marketing', 'none', 'healthcare', 'retired', 'salesman', 'doctor'],
      dtype=object)

In [50]:
df['zip_code'].unique()

array(['85711', '94043', '32067', '43537', '15213', '98101', '91344',
       '05201', '01002', '90703', '30329', '06405', '29206', '55106',
       '97301', '10309', '06355', '37212', '02138', '95660', '30068',
       '40206', '48197', '94533', '55107', '21044', '30030', '55369',
       '55436', '10003', '78741', '27510', '42141', '42459', '93117',
       '55105', '54467', '01040', '27514', '80525', '17870', '20854',
       '46260', '50233', '46538', '07102', '12550', '76111', '52245',
       '16509', '55414', '66315', '01331', '84010', '52246', '08403',
       '06472', '30040', '97214', '75240', '43202', '48118', '80521',
       '60402', '22904', '55337', '60067', '98034', '73034', '41850',
       'T8H1N', '08816', '02215', '29379', '61801', '03755', '52241',
       '21218', '22902', '44133', '20003', '46005', '89503', '11701',
       '68106', '78155', '01913', '23112', '71457', '10707', '75206',
       '98006', '90291', '63129', '90254', '05146', '30220', '55108',
       '55125', '60466', '63130', '55423', '77840', '90630', '60613',
       '95032', '75013', '17110', '97232', '16125', '90210', '67401',
       '06260', '99603', '22206', '20008', '60615', '22202', '20015',
       '73439', '20009', '07039', '60115', '15237', '94612', '78602',
       '80236', '38401', '97365', '84408', '53211', '08904', '32250',
       '36117', '08832', '20910', 'V3N4P', '83814', '02143', '97006',
       '17325', '02139', '48103', '68767', '60641', '53703', '11217',
       '08360', '70808', '27606', '55346', '66215', '55104', '15610',
       '97212', '80123', '53715', '55113', 'L9G2B', '80127', '53705',
       '30067', '78750', '22207', '22306', '52302', '21911', '07030',
       '19104', '49512', '20755', '60202', '33884', '27708', '76013',
       '97403', '00000', '16801', '29440', '95014', '95938', '95161',
       '90840', '49931', '02154', '93555', '75094', '17604', '93402',
       'E2A4H', '60201', '32301', '10960', '06371', '53115', '92037',
       '01720', '85710', '03060', '32605', '61401', '55345', '11231',
       '63033', '11727', '06513', '43212', '78205', '20685', '27502',
       '47906', '43512', '58202', '92103', '60659', '22003', '22903',
       '14476', '01080', '99709', '98682', '94702', '22973', '53214',
       '63146', '44124', '95628', '20784', '20001', '31404', '55109',
       '28734', '20770', '37235', '84103', '95110', '85032', '07733',
       '42647', '07029', '39042', '77005', '77801', '48823', '89801',
       '85202', '78264', '90064', '84601', '78756', '83716', '19422',
       '43201', '63119', '22932', '53706', '10016', '92064', '95064',
       '55406', '30033', '85251', '06059', '20057', '55305', '92629',
       '53713', '15217', '31211', '23226', '94619', '93550', '44106',
       '94703', '60804', '92110', '50325', '16803', '98103', '01581',
       '63108', '55439', '77904', '14853', '71701', '94086', '73132',
       '55454', '95076', '70802', '91711', '73071', '02110', '60035',
       '08043', '18301', '77009', '13210', '06518', '22030', '24060',
       '55413', '50613', '19149', '02176', '15235', '11101', '06779',
       '40504', 'V0R2M', '30002', '33775', '42101', '10522', '59717',
       '37901', '44405', '30093', '94117', '94143', '76059', '45660',
       '61455', '49938', '28480', '60135', '92688', '98133', '10022',
       '98027', '44074', '85233', '87501', '01810', '50670', '37411',
       '92113', '91335', '08534', '99206', '66046', '55116', '78746',
       '37777', '10010', '18015', '02859', '98117', '55117', '94608',
       '01824', '75204', '45218', '43221', '37412', '36106', '83702',
       '85016', '84604', '59801', '83686', '96819', '44092', '94551',
       '60008', '92374', '78213', '84107', '95129', '06811', '10019',
       '93109', '03261', '61755', '98225', '94025', '44691', '15222',
       '78212', '38115', '92626', '21206', '43215', '02140', '91606',
       '55422', '58644', '01602', '85258', '29205', '98199', '50311',
       '11211', '49705', '60007', '17345', '43204', '20817', '48076',
       '55013', '85282', '33308', '53202', '92653', '10021', '55021',
       '11758', '48446', '28018', '06333', '97330', '83709', '31820',
       '30011', 'Y1A6B', '29201', '60630', '98102', '02918', '75218',
       '94583', '05001', '90804', '91201', '02341', '78628', '77459',
       '87544', '94708', '93711', '75230', '60440', '02125', '55409',
       '98257', '37771', '40256', '21208', '95821', '93101', '92121',
       '21012', 'V5A2B', '53711', '94618', '60090', '49428', '03052',
       '50112', '55408', '75006', '94305', '10025', '23092', '92115',
       '20657', '03869', '28450', '19382', '10011', '98038', '21250',
       '20090', '26241', '20707', '49508', '55320', '12603', '02146',
       '55443', '04102', '02159', '19711', '97124', '12180', '44224',
       '94040', '97408', '92705', '02324', '05464', '80302', '30078',
       '21010', '80303', '84302', '60515', '95123', '29464', '08052',
       '22911', '14534', '95468', '45680', '95453', '68147', '62901',
       '23227', '30606', '63132', '60005', '20879', '32707', '94591',
       '14627', '01915', '91903', '01945', '48911', '53188', '46032',
       '98281', '77845', 'M7A1A', '17961', '94131', '93003', '29631',
       '27511', '98501', '79508', '14216', '93063', '90034', '82435',
       '92093', '97520', 'M4J2K', '31909', '77073', '84116', '43085',
       'R3T5K', '02320', '99687', '34656', '47905', '11787', '33716',
       '63044', '21227', '77008', '79070', '29678', '80227', '27705',
       '11201', '44212', '44134', '81648', '14850', '60187', '20723',
       '19807', '08034', '94306', '38866', '23237', '48043', '74101',
       '01940', '12065', '60626', '95521', '55122', '63645', '51250',
       '45810', '91351', '39762', '02903', '78739', '60657', '10314',
       '78704', '54248', '77380', '98121', '19102', '19341', '94115',
       '55412', '61820', '01970', '21114', '91919', '90095', '22906',
       '28814', '32712', '99835', '61462', '54302', '90405', '97208',
       '55128', '23509', '26506', '27713', '60476', '45439', '63304',
       '60089', '18053', '85210', '06365', '94920', '77042', '06906',
       '96754', '76309', '56321', '89104', '91105', '54494', '19146',
       '96349', 'N4T1A', '92020', '15203', '54901', '07204', '55343',
       '91206', '44265', '84105', '64118', 'V0R2H', '16506', '11238',
       '17331', '94403', '40243', '80538', '56567', '32114', '70403',
       '98405', '85719', '98072', '95403', '73162', '29210', '92660',
       '47024', '19047', '93612', '94720', '80919', '32303', '21201',
       '97007', '90247', '68503', '14211', '97302', '95050', '02113',
       '62903', '33066', '12866', '06927', '15232', '27105', '80027',
       '90036', '51157', '01960', 'K7L5J', '94560', '48825', '33205',
       '77081', '91040', '23322', '01754', '98620', '05779', '55420',
       '80913', '20064', '12205', '85281', '57197', '08610', '33755',
       '62522', '64131', '19716', '92154', '34105', '90016', '30803',
       '80526', '73013', '76234', '02136', '12345', '28806', '60152',
       '40205', '37725', '53144', '50322', '15017', '05452', '77048',
       '80228', '80209', '53066', '33765', '90019', '64153', '11577',
       '10018', '01375', '90814', '47401', '93055', '95662', '97405',
       '47130', '55417', '25652', '78390', '29646', '40515', '04988',
       '97215', 'V1G4L', '09645', '06492', '48322', '14085', '13820',
       '63021', '60302', '92507', '55303', '65203', '44648', '74078',
       '33763', '37076', '35802', '20902', '77504', '43017', '40503',
       '50266', '95316', '27249', '17036', '03062', '45243', '95823',
       '74075', '91505', '33484', '18505', 'L1V3W', '97203', '20850',
       '61073', '30350', '70124', '68504', '53171', '29301', '53210',
       '06512', '76201', '08105', '60614', 'N2L5N', '20006', '70116',
       '90008', '98801', 'E2E3R', '11753', '49036', '01701', '55428',
       '07310', '33556', '06437', '48105', '66221', '32789', '55038',
       '33319', '97229', '78209', '77841'], dtype=object)

### Step 14. Summarize only the occupation column

In [51]:
df["occupation"].value_counts()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

### Step 15. What is the mean age of users?

In [54]:
df["age"].value_counts().mean()

np.float64(15.459016393442623)

### Step 16. What is the age with least occurrence?

In [55]:
df["age"].value_counts().min()

np.int64(1)